# Welcome to the BungeeRelay configuration file.
# These small comments serve as an explanation of what each value is and general guidance.

# Please remember the following before you begin:
# - This plugin is not a standalone IRCd, and will not function without an InspIRCd
#   instance to link to. You can find InspIRCd at http://inspircd.org/
# - This plugin is currently only compatible with recent versions of InspIRCd. This is
#   the only type of IRCd you should use with this plugin, NOT UnrealIRCd etc.
# - Make sure you enable m_spanningtree.so in modules.conf.

# This section mainly uses info from your link block, in links.conf.
server:
  # The address the plugin needs to connect to.
  # Put in 127.0.0.1 if the IRC is on the same box.
  host: "127.0.0.1"

  # The port the plugin needs to connect to.
  # The "port" in your link block.
  port: 7000

  # The "name" in your link block.
  servername: "bungee.example.org"

  # The friendly name for this server. It can be whatever you please.
  realname: "BungeeCord running BungeeRelay"

  # The password the plugin expects to receive.
  # The "sendpass" in your link block.
  recvpass: "pass"

  # The password the plugin will send to the server.
  # The "recvpass" in your link block.
  sendpass: "pass"

  # The length of time to wait before automatically reconnecting, should connection to the
  # IRC server be lost. The time is in milliseconds. Set to -1 for no reconnect attempt.
  reconnect: 3000

  # If you want to use 1 single channel for every BungeeCord server, set this value to the
  # name of the channel (e.g. "#minecraft"). However, if you wish to have separate channels
  # for each BungeeCord server (recommended!), LEAVE THIS BLANK.
  channel: ""

  # If you wish to use different channels for different servers, you can apply a prefix to
  # the channel, such as "#mc-" and then the name. If you don't want a prefix, leave it as
  # "#". This value is ignored if you put something in "channel" above.
  chanprefix: "#"

  # If the topic should be set to something in every channel that is being relayed to, enter
  # a topic below. Leave blank for no change. You can use {SERVERNAME} for the name of the
  # current server in BungeeCord, but only if "channel" above is blank, of course.
  topic: "Minecraft Server Chat for {SERVERNAME}"

  # This value determines whether the player should be moved/kicked from the server if they
  # are kicked through IRC.
  kick: true

  # This value determines whether the player should be moved/kicked from the server if they
  # connect through a banned mask (channel mode +b). Compares both their nick and their
  # connection address.
  # NOTE: I recommend you set this to false for now while a better system is being worked on,
  # as currently this ban system is fairly buggy and should not be relied on. W.I.P!
  ban: false

  # If you wish for the bot to automatically join a staff channel, specify the channel name.
  # For no automatic staff channel, leave this blank.
  staff: "#staff"

  # If you wish the staff channel to have a topic set on join, specify it the topic here.
  # This value will be ignored if the value of "staff" above is blank.
  stafftopic: "Minecraft Server Staff"

  # The modes that will automatically be set on the staff channel specified above. +O is
  # recommended, since with this mode only IRC Ops will be able to join. You could also
  # use another mode such as +k (channel key) or +i (invite only, if you have Services).
  # This value will be  ignored if the value of "staff" above is blank.
  staffmodes: "+O"

  # The visible host that will represent each Minecraft user over IRC. All users will be able
  # to see this host, but IRC network administrators will still be able to see the real
  # hostname and IP address for Minecraft users (likely through /whois). You can specify the
  # parameters {UUID}, {PLAYER} and {HOST} (the UUID, the username and the real hostmask).
  # It is recommended to use these parameters so that hostmasks are unique. If you do not
  # wish ANY adjustments to be made to the host, just set the value simply to "{HOST}".
  userhost: "Minecraft/{UUID}"

  # You can set a prefix and suffix to the nicknames of Minecraft IRC users. This can be
  # helpful for users to distinguish between Minecraft players and normal IRC users.
  # For example, if usersuffix was "/minecraft", I appear on IRC as "Dead_i/minecraft"
  userprefix: ""
  usersuffix: "|mc"

  # Set to "true" to make BungeeRelay say each message it receives raw in console.
  # Used for debugging purposes only. For general use, leave "false".
  debug: false

# This section contains the format of each message going to your Minecraft servers.
# Accepts colour codes, and each parameter is capital and surrounded in curly brackets.
# Leaving a particular message empty is acceptable.
formats:
  # The ident of a user connecting to IRC.
  # Parameters: {IDENT}
  ident: "minecraft"

  # How public messages sent from IRC will appear in Minecraft.
  # Parameters: sender, message
  msg: "<&7[IRC]&r {SENDER}> {MESSAGE}"

  # How public messages sent with /me will appear in Minecraft.
  # Parameters: sender, message
  me: "&d* [IRC] {SENDER} {MESSAGE}"

  # How private messages sent to a user will appear in Minecraft.
  # Parameters: sender, message
  privatemsg: "&7[PM]&r <&7[IRC]&r {SENDER}> {MESSAGE}"

  # How private messages appear if it was sent with /me in Minecraft.
  privateme: "&7[PM] &d* [IRC] {SENDER} {MESSAGE}"

  # The output of the global /say command in Minecraft
  # Parameters: message
  saycommand: "&d[SERVER] {MESSAGE}"

  # How mode changes will appear in Minecraft
  # Parameters: sender, mode
  mode: "&7{SENDER} set mode {MODE}"

  # How nick changes will appear in Minecraft
  # Parameters: old_nick, new_nick
  nick: "&7{OLD_NICK} is now know as &7{NEW_NICK}"

  # How joins will appear in Minecraft
  # Parameters: sender
  join: "&7{SENDER} joined the channel"

  # How parts (leaving the channel) will appear in Minecraft
  # Parameters: sender, reason
  part: "&7{SENDER} left the channel ({REASON})"

  # How Minecraft quits will appear in IRC
  # Parameters: sender
  mcquit: "{SENDER} logged out of Minecraft"

  # How IRC quits will appear in Minecraft
  # Parameters: sender, reason
  ircquit: "&7{SENDER} left IRC ({REASON})"

  # How kills will appear in Minecraft
  # Parameters: sender, target, reason
  kill: "&7{SENDER} killed {TARGET} from the channel ({REASON})"

  # How kicks will appear in Minecraft
  # Parameters: sender, target, reason
  kick: "&7{SENDER} kicked {TARGET} from the channel ({REASON})"

  # The message players will be disconnected with if they are killed through IRC.
  # Parameters: sender, target, reason
  disconnectkill: "&7You were killed by {SENDER} through IRC.&r\n\n{REASON}"

  # The message players will be disconnected with if they are kicked through IRC.
  # Parameters: sender, target, reason
  disconnectkick: "&7You were kicked by {SENDER} through IRC.&r\n\n{REASON}"
